// main_glfw.cpp - JuggleSim on macOS (and other non-Windows systems): the entry point and the
// platform functions (platform.h), using a GLFW window with an OpenGL 3.3 core-profile context
// and ImGui's GLFW backend. Everything else is in app.cpp, shared with Windows.
//
// The built-in pattern library is compiled in from a source file the build script generates
// from data/patterns.txt (kBuiltInPatternText).

#include "app.h"
#include "platform.h"

#include "imgui.h"
#include "imgui_impl_glfw.h"

#ifndef GLFW_INCLUDE_NONE
#define GLFW_INCLUDE_NONE  // (OpenGL comes from gl_funcs.h, where it's needed)
#endif
#include <GLFW/glfw3.h>

#include <algorithm>
#include <chrono>
#include <cstdio>
#include <string>
#include <thread>

// Generated by the build from data/patterns.txt.
extern const char kBuiltInPatternText[];

namespace {

GLFWwindow* g_window = nullptr;
bool g_closeRequested = false;

void reportGlfwError(int code, const char* description) {
    std::fprintf(stderr, "GLFW error %d: %s\n", code, description);
}

}  // namespace

// ---- platform.h

bool platformPollEvents() {
    glfwPollEvents();
    // Closing (the close button, Cmd+Q) only asks: the app decides, since it may ask about
    // unsaved work first (platformTakeCloseRequest).
    if (glfwWindowShouldClose(g_window)) {
        g_closeRequested = true;
        glfwSetWindowShouldClose(g_window, GLFW_FALSE);
    }
    return true;
}

SpaceMouseState platformSpaceMouse() { return SpaceMouseState(); }  // (not read on this platform yet)

bool platformTakeCloseRequest() {
    const bool requested = g_closeRequested;
    g_closeRequested = false;
    return requested;
}

void platformSetWindowTitle(const char* title) { glfwSetWindowTitle(g_window, title); }

bool platformIsMinimized() { return glfwGetWindowAttrib(g_window, GLFW_ICONIFIED) != 0; }

void platformSleepMilliseconds(int milliseconds) {
    std::this_thread::sleep_for(std::chrono::milliseconds(milliseconds));
}

void platformNewFrame() { ImGui_ImplGlfw_NewFrame(); }

void platformFramebufferSize(int* width, int* height) { glfwGetFramebufferSize(g_window, width, height); }

void platformSwapBuffers() { glfwSwapBuffers(g_window); }

void platformShowError(const char* title, const char* message) {
    // There's no simple native message box without Cocoa code; the terminal (or Console.app,
    // for a double-clicked app) shows this.
    std::fprintf(stderr, "%s: %s\n", title, message);
}

std::string platformBuiltInPatternText() { return std::string(kBuiltInPatternText); }

void* platformGetProcAddress(const char* name) { return reinterpret_cast<void*>(glfwGetProcAddress(name)); }

int main() {
    glfwSetErrorCallback(reportGlfwError);
    if (!glfwInit()) return 1;

    // OpenGL 3.3, core profile: the newest macOS offers is 4.1, and it only offers core
    // profiles (which must be forward-compatible).
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GLFW_TRUE);
    glfwWindowHint(GLFW_DEPTH_BITS, 24);
    glfwWindowHint(GLFW_STENCIL_BITS, 8);
    // Window sizes are in points; on a Retina display the framebuffer has more pixels.
    glfwWindowHint(GLFW_SCALE_TO_MONITOR, GLFW_TRUE);

    // 1600 x 900, or less if the screen is smaller (a laptop's), leaving room for the menu bar
    // and Dock.
    int width = 1600, height = 900;
    if (GLFWmonitor* monitor = glfwGetPrimaryMonitor()) {
        int areaX = 0, areaY = 0, areaWidth = 0, areaHeight = 0;
        glfwGetMonitorWorkarea(monitor, &areaX, &areaY, &areaWidth, &areaHeight);
        if (areaWidth > 0 && areaHeight > 0) {
            width = std::min(width, areaWidth * 9 / 10);
            height = std::min(height, areaHeight * 9 / 10);
        }
    }
    g_window = glfwCreateWindow(width, height, "JuggleSim", nullptr, nullptr);
    if (!g_window) {
        platformShowError("JuggleSim", "Couldn't create a window with an OpenGL 3.3 context.");
        glfwTerminate();
        return 1;
    }
    glfwMakeContextCurrent(g_window);
    glfwSwapInterval(1);  // vsync

    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGui_ImplGlfw_InitForOpenGL(g_window, true);

    const int exitCode = runApp();

    ImGui_ImplGlfw_Shutdown();
    ImGui::DestroyContext();
    glfwDestroyWindow(g_window);
    glfwTerminate();
    return exitCode;
}
